items:
- model_name: qwen2.5-0.5B-p256-ax630c
  type: llm
- model_name: internvl2.5-1B-364-ax630c
  type: vlm
- model_name: whisper-tiny
  type: whisper
- model_name: whisper-base
  type: whisper
- model_name: whisper-small
  type: whisper
- model_name: sherpa-ncnn-streaming-zipformer-20M-2023-02-17
  type: asr
- model_name: sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23
  type: asr
- model_name: sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01
  type: kws
- model_name: sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01
  type: kws
- model_name: melotts-zh-cn
  type: melotts
- model_name: single_speaker_english_fast
  type: tts
- model_name: single_speaker_fast
  type: tts
- model_name: yolo11n
  type: yolo
- model_name: yolo11n-seg
  type: yolo
- model_name: yolo11n-pose
  type: yolo