# component2/SConscript
Import("env")
import os
from pathlib import Path

with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())

_SDK_PATH = os.path.normpath(
    os.environ.get("SDK_PATH", str(Path(os.getcwd()) / ".." / ".."))
)

env["GIT_REPO_LISTS"]["openai-api"] = {
    "url": "https://github.com/ZHEQIUSHUI/openai-api.cpp.git",
    "commit": "127f3e75054a733ca1b903ff1f8ec600b90cb6b0",
    "path": str(Path(_SDK_PATH) / "github_source" / "openai-api.cpp"),
}

if "CONFIG_AX_OPENAI_API_ENABLED" in os.environ:
    check_component("openai-api")
    SRCS = []
    INCLUDE = []
    PRIVATE_INCLUDE = []
    REQUIREMENTS = []
    STATIC_LIB = []
    DYNAMIC_LIB = []
    DEFINITIONS = []
    DEFINITIONS_PRIVATE = []
    LDFLAGS = []
    LINK_SEARCH_PATH = []

    INCLUDE += [
        os.path.join(env["GIT_REPO_LISTS"]["openai-api"]["path"], "include"),
    ]

    env["COMPONENTS"].append(
        {
            "target": os.path.basename(env["component_dir"]),
            "SRCS": SRCS,
            "INCLUDE": INCLUDE,
            "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
            "REQUIREMENTS": REQUIREMENTS,
            "STATIC_LIB": STATIC_LIB,
            "DYNAMIC_LIB": DYNAMIC_LIB,
            "DEFINITIONS": DEFINITIONS,
            "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
            "LDFLAGS": LDFLAGS,
            "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
            "REGISTER": "static",
        }
    )