import os

Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())

# env.Append(CXXFLAGS=['-O3', '-fopenmp', '-std=c++17'])
SRCS = Glob('src/*.c*')
INCLUDE = [ADir('include'), ADir('.')]
PRIVATE_INCLUDE = []
REQUIREMENTS = ['pthread', 'utilities', 'ax_msp', 'gomp', 'eventpp', 'StackFlow', 'eigen', 'sherpa-onnx']
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []

DEFINITIONS += ['-O3', '-fopenmp', '-std=c++17']
LDFLAGS+=['-Wl,-rpath=/opt/m5stack/lib', '-Wl,-rpath=/usr/local/m5stack/lib', '-Wl,-rpath=/usr/local/m5stack/lib/gcc-10.3', '-Wl,-rpath=/opt/lib', '-Wl,-rpath=/opt/usr/lib', '-Wl,-rpath=./']
LINK_SEARCH_PATH += [ADir('../static_lib')]
REQUIREMENTS += ['ax_engine', 'ax_interpreter', 'ax_sys']
REQUIREMENTS += ['samplerate']
REQUIREMENTS += ['tts']

INCLUDE += [ADir('src/runner/eigen-3.4.0'), 
            ADir('src/runner/src/tn/header'), 
            ADir('src/runner/include'), 
            ADir('src/runner/src/header'),
            ]

LINK_SEARCH_PATH += [ADir('../static_lib/sherpa/onnx')]


LDFLAGS += ['-l:libonnxruntime.so.1.23.2',
            '-l:libsherpa-onnx-core.a',
            '-l:libkaldi-native-fbank-core.a',
            '-l:libkissfft-float.a',
            '-l:libsherpa-onnx-fst.a',
            '-l:libsherpa-onnx-kaldifst-core.a', 
            '-l:libsherpa-onnx-fstfar.a', 
            '-l:libpiper_phonemize.a',
            '-lespeak-ng', 
            '-l:libucd.a'
            ]
            
STATIC_FILES += Glob('mode_*.json')

env['COMPONENTS'].append({'target':'llm_tts-1.7',
                          'SRCS':SRCS,
                          'INCLUDE':INCLUDE,
                          'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                          'REQUIREMENTS':REQUIREMENTS,
                          'STATIC_LIB':STATIC_LIB,
                          'DYNAMIC_LIB':DYNAMIC_LIB,
                          'DEFINITIONS':DEFINITIONS,
                          'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                          'LDFLAGS':LDFLAGS,
                          'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                          'STATIC_FILES':STATIC_FILES,
                          'REGISTER':'project'
                          })
