import os

Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())


SRCS = append_srcs_dir(ADir('src'))
INCLUDE = [ADir('include'), ADir('.')]
PRIVATE_INCLUDE = [ADir('../include')]
REQUIREMENTS = ['pthread','atomic','rt', 'dl', 'm', 'ax_msp', 'axcl', 'utilities', 'eventpp', 'StackFlow', 'tokenizer', 'openai-api', 'SimpleCV']
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []

DEFINITIONS += ['-O2']
DEFINITIONS += ['-std=c++17']
LDFLAGS+=['-Wl,-rpath=/opt/m5stack/lib', '-Wl,-rpath=/usr/local/m5stack/lib', '-Wl,-rpath=/usr/local/m5stack/lib/gcc-10.3', '-Wl,-rpath=/opt/lib', '-Wl,-rpath=/opt/usr/lib', '-Wl,-rpath=./']
# REQUIREMENTS += ['ax_engine', 'ax_interpreter', 'ax_sys', 'utilities']
REQUIREMENTS += ['spdlog', 'axcl_pcie_dma', 'axcl_pcie_msg', 'axcl_token', 'axcl_comm', 'axcl_pkg', 'axcl_rt', 'utilities']
LINK_SEARCH_PATH += [ADir('../static_lib')]


INCLUDE += [ADir('src/runner'), ADir('src/runner/utils'), ADir('src/runner/ax_model_runner]'), ADir('src/runner/magic_enum/include')]
STATIC_LIB += [AFile('../static_lib/libopenai_api.a'), AFile('../static_lib/libsimplecv.a'), AFile('../static_lib/libtokenizer.a')]

STATIC_FILES += Glob('models/mode_*.json')

IGNORE_FILES = []
IGNORE_FILES += ['llm']

import json
if not os.path.exists('../dist'):
    os.makedirs('../dist')
ignore = {'ignore':[]}
try:
    with open('../dist/fileignore', 'a+') as f:
        f.seek(0)
        ignore = json.load(f)
except:
    pass
ignore['ignore'] += IGNORE_FILES
ignore['ignore'] = list(set(ignore['ignore']))
with open('../dist/fileignore', 'w') as f:
    json.dump(ignore, f, indent=4)

env['COMPONENTS'].append({'target':'llm_llm2-1.12',
                          'SRCS':SRCS,
                          'INCLUDE':INCLUDE,
                          'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                          'REQUIREMENTS':REQUIREMENTS,
                          'STATIC_LIB':STATIC_LIB,
                          'DYNAMIC_LIB':DYNAMIC_LIB,
                          'DEFINITIONS':DEFINITIONS,
                          'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                          'LDFLAGS':LDFLAGS,
                          'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                          'STATIC_FILES':STATIC_FILES,
                          'REGISTER':'project'
                          })

