# component2/SConscript
Import("env")
import os
from pathlib import Path

with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())

_SDK_PATH = os.path.normpath(
    os.environ.get("SDK_PATH", str(Path(os.getcwd()) / ".." / ".."))
)

env["GIT_REPO_LISTS"]["sherpa-ncnn"] = {
    "url": "https://github.com/Abandon-ht/sherpa-ncnn.git",
    "commit": "c61e50d61e9fbed5972afa4d95bc560e168affe2",
    "path": str(Path(_SDK_PATH) / "github_source" / "sherpa-ncnn"),
}

if "CONFIG_EIGEN_ENABLED" in os.environ:
    check_component("sherpa-ncnn")
    SRCS = []
    INCLUDE = []
    PRIVATE_INCLUDE = []
    REQUIREMENTS = []
    STATIC_LIB = []
    DYNAMIC_LIB = []
    DEFINITIONS = []
    DEFINITIONS_PRIVATE = []
    LDFLAGS = []
    LINK_SEARCH_PATH = []

    INCLUDE += [
        os.path.join(env["GIT_REPO_LISTS"]["sherpa-ncnn"]["path"]),
    ]

    env["COMPONENTS"].append(
        {
            "target": os.path.basename(env["component_dir"]),
            "SRCS": SRCS,
            "INCLUDE": INCLUDE,
            "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
            "REQUIREMENTS": REQUIREMENTS,
            "STATIC_LIB": STATIC_LIB,
            "DYNAMIC_LIB": DYNAMIC_LIB,
            "DEFINITIONS": DEFINITIONS,
            "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
            "LDFLAGS": LDFLAGS,
            "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
            "REGISTER": "static",
        }
    )