import os

Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())

SRCS = append_srcs_dir(ADir('src'))
INCLUDE = [ADir('include'), ADir('.')]
PRIVATE_INCLUDE = []
REQUIREMENTS = ['pthread', 'dl', 'utilities', 'eventpp', 'StackFlow', 'single_header_libs', 'axcl']
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []

if "CONFIG_AXCL_ENABLED" in os.environ:
    if "CONFIG_RASPBERRYPI_ENV" in os.environ:
        if "CONFIG_RPI_ENV_BOOKWORM" in os.environ:
            python_venv = check_wget_down(
                "https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/linux/llm/m5stack_llm-kws-python-axcl-rsp-bookworm-venv_v1.7.tar.gz",
                "m5stack_llm-kws-python-axcl-rsp-bookworm-venv_v1.7.tar.gz",
            )
        elif "CONFIG_RPI_ENV_TRIXIE" in os.environ:
            python_venv = check_wget_down(
                "https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/linux/llm/m5stack_llm-kws-python-axcl-rsp-trixie-venv_v1.7.tar.gz",
                "m5stack_llm-kws-python-axcl-rsp-trixie-venv_v1.7.tar.gz",
            )
else:
    python_venv = check_wget_down("https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/linux/llm/m5stack_llm-kws-python-venv_v1.6.tar.gz", 'm5stack_llm-kws-python-venv_v1.6.tar.gz')

DEFINITIONS += ['-std=c++17']
LDFLAGS+=['-Wl,-rpath=/opt/m5stack/lib', '-Wl,-rpath=/usr/local/m5stack/lib', '-Wl,-rpath=/usr/local/m5stack/lib/gcc-10.3', '-Wl,-rpath=/opt/lib', '-Wl,-rpath=/opt/usr/lib', '-Wl,-rpath=./']
REQUIREMENTS += ['axcl_rt', 'axcl_pkg', 'axcl_comm', 'spdlog', 'axcl_token', 'axcl_pcie_msg', 'axcl_pcie_dma', 'utilities']
LINK_SEARCH_PATH += [ADir('../static_lib')]

INCLUDE += [ADir('src/runner'),
            ADir('../static_lib/include/sherpa'),
            ADir('../static_lib/include/sherpa/fbank'),
            ADir('../static_lib/include/sherpa/sherpa-onnx'),
            ADir('../static_lib/include/sherpa/sherpa-onnx/onnxruntime-src'),
            ADir('../static_lib/eigen-src'),
            ADir('../static_lib/include/sherpa/sherpa-onnx/openfst-src')
            ]

LINK_SEARCH_PATH += [ADir('../static_lib/sherpa/onnx')]
REQUIREMENTS += ['onnxruntime']

LDFLAGS += ['-l:libsherpa-onnx-core.a', '-l:libkaldi-native-fbank-core.a', '-l:libkissfft-float.a',
            '-l:libkaldi-decoder-core.a', '-l:libssentencepiece_core.a']


STATIC_FILES += [os.path.join(python_venv, 'sherpa-onnx')]
STATIC_FILES += Glob('llm-kws_text2token.py')
STATIC_FILES += Glob('mode_*.json')

IGNORE_FILES = []
IGNORE_FILES += ['sherpa-onnx']

import json
if not os.path.exists('../dist'):
    os.makedirs('../dist')
ignore = {'ignore':[]}
try:
    with open('../dist/fileignore', 'a+') as f:
        f.seek(0)
        ignore = json.load(f)
except:
    pass
ignore['ignore'] += IGNORE_FILES
ignore['ignore'] = list(set(ignore['ignore']))
with open('../dist/fileignore', 'w') as f:
    json.dump(ignore, f, indent=4)

env['COMPONENTS'].append({'target':'llm_kws-1.9',
                          'SRCS':SRCS,
                          'INCLUDE':INCLUDE,
                          'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                          'REQUIREMENTS':REQUIREMENTS,
                          'STATIC_LIB':STATIC_LIB,
                          'DYNAMIC_LIB':DYNAMIC_LIB,
                          'DEFINITIONS':DEFINITIONS,
                          'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                          'LDFLAGS':LDFLAGS,
                          'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                          'STATIC_FILES':STATIC_FILES,
                          'REGISTER':'project'
                          })
